### ISSUE TITLE
Use SAP HANA as the Database for a CAP Java Application

### ISSUE THREAD

**Issue by mts2605** [SAPDocuments/Issues#105]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-hana-db.html
--------------------------

Step 3 - ad 4: (cds deploy --to hana:bookstore-hana)
When doing this, there is error(s):

_
user: bookstore $ cds deploy --to hana:bookstore-hana
[cds.deploy] - Starting deploy to SAP HANA ...

[cds.deploy] - Creating build tasks
[cds.deploy] - Running build

[cds.deploy] - Using container bookstore-hana

[cds.deploy] - Running 'cf create-service hana hdi-shared bookstore-hana' with options {}
Creating service instance bookstore-hana in org 923d2516trial / space dev as "XYZ"@gmail.com...
OK

Service bookstore-hana already exists 

[cds.deploy] - Running 'cf create-service-key bookstore-hana bookstore-hana-key -c {"permissions":"development"}' with options {}
Creating service key bookstore-hana-key for service instance bookstore-hana as "XYZ"@gmail.com...
Service broker error: Service broker hana-broker failed with: Service instance 'ef438281-8dad-460a-88ae-a8570dbbf854' not found.
FAILED
[ERROR] [cds.deploy] - Could not create service key bookstore-hana-key.
    at HanaDeployer._validateServiceKey (/extbin/npm/globals/lib/node_modules/@sap/cds/bin/deploy/to-hana/hana.js:182:13)
    at HanaDeployer._getOrCreateCFService (/extbin/npm/globals/lib/node_modules/@sap/cds/bin/deploy/to-hana/hana.js:151:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)

END OF ERROR
__

Even though one line states : Service bookstore-hana already exists  - There is error when looking at the instance from the subaccount. Error there "Creation failed"
Did also try to create instance from subaccount. Also error.
Could it be problem with service key(s), or...?

**Comment by mts2605** [comment]
Forget this - when I created the instance from SCP Cockpit, the message I got was:

[cds.deploy] - Done.
user: bookstore $  

_
;-)
