### ISSUE TITLE
Create an SAP HANA Database Project failed when deploying from BAS

### ISSUE THREAD

**Issue by Nuube** [SAPDocuments/Issues#120]
Tutorial: https://developers.sap.com/tutorials/hana-cloud-create-db-project.html
--------------------------

When I tried to deploy the initial database, i got an  error

```
Deployment to container AUDIT01_HDI_AUDITDB_1 failed - error: HDI make failed [Deployment ID: none].
Error: HDI make failed
(1s 828ms)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js "--exit"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deploy@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-02-04T10_42_35_150Z-debug.log
```

`cat ../../.npm/_logs/2021-02-04T10_40_20_767Z-debug.log `

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/nodejs/node-v10.23.1-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--exit' ]
2 info using npm@6.14.10
3 info using node@v10.23.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle deploy@~prestart: deploy@
6 info lifecycle deploy@~start: deploy@
7 warn lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.23.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
8 verbose lifecycle deploy@~start: unsafe-perm in lifecycle true
9 verbose lifecycle deploy@~start: PATH: /opt/nodejs/node-v10.23.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/user/projects/Audit01/auditdb/node_modules/.bin:/home/user/.node_modules_global/bin:/extbin/bin:/extbin/npm/docker/bin:/extbin/npm/globals/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/curl/bin
10 verbose lifecycle deploy@~start: CWD: /home/user/projects/Audit01/auditdb
11 silly lifecycle deploy@~start: Args: [ '-c', 'node node_modules/@sap/hdi-deploy/deploy.js "--exit"' ]
12 silly lifecycle deploy@~start: Returned: code: 1  signal: null
13 info lifecycle deploy@~start: Failed to exec start script
14 verbose stack Error: deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js "--exit"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/opt/nodejs/node-v10.23.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/opt/nodejs/node-v10.23.1-linux-x64/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid deploy@
16 verbose cwd /home/user/projects/Audit01/auditdb
17 verbose Linux 5.4.0-4-cloud-amd64
18 verbose argv "/opt/nodejs/node-v10.23.1-linux-x64/bin/node" "/usr/local/bin/npm" "start" "--" "--exit"
19 verbose node v10.23.1
20 verbose npm  v6.14.10
21 error code ELIFECYCLE
22 error errno 1
23 error deploy@ start: `node node_modules/@sap/hdi-deploy/deploy.js "--exit"`
23 error Exit status 1
24 error Failed at the deploy@ start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true 
```

**Comment by Nuube** [comment]
Ok, It was apperantly a syntax error in one of the files (.hdbindex in this case).

The error message wasn't really helpful though.
