### ISSUE TITLE
Deploy Your First SAPUI5 App

### ISSUE THREAD

**Issue by kyungwoh** [SAPDocuments/Issues#174]
Tutorials: https://developers.sap.com/tutorials/appstudio-sapui5-create.html
--------------------------

[Fiori] build fails

```
> Executing task: mbt build -s '/home/user/projects/fiori'; sleep 2; <

[2021-02-18 20:22:51]  INFO Cloud MTA Build Tool version 1.1.0
[2021-02-18 20:22:51]  INFO generating the "Makefile_20210218202251.mta" file...
[2021-02-18 20:22:51]  INFO done
[2021-02-18 20:22:51]  INFO executing the "make -f Makefile_20210218202251.mta p=cf mtar= strict=true mode=" command...
[2021-02-18 20:22:51]  INFO validating the MTA project
[2021-02-18 20:22:51]  INFO validating the MTA project
[2021-02-18 20:22:51]  INFO building the "fiori" module...
[2021-02-18 20:22:51]  INFO executing the "npm install" command...
....npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.23.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keytar@7.2.0 install /home/user/projects/fiori/node_modules/keytar
> prebuild-install || npm run build

prebuild-install WARN install libsecret-1.so.0: cannot open shared object file: No such file or directory
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.23.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> keytar@7.2.0 build /home/user/projects/fiori/node_modules/keytar
> node-gyp rebuild

./bin/sh: 1: pkg-config: not found
gyp: Call to 'pkg-config --libs-only-l libsecret-1' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/opt/nodejs/node-v10.23.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-4-cloud-amd64
gyp ERR! command "/opt/nodejs/node-v10.23.1-linux-x64/bin/node" "/opt/nodejs/node-v10.23.1-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/projects/fiori/node_modules/keytar
gyp ERR! node -v v10.23.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! keytar@7.2.0 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the keytar@7.2.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-02-18T20_22_56_471Z-debug.log
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/@ui5/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@7.2.0 (node_modules/keytar):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: keytar@7.2.0 install: `prebuild-install || npm run build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 1297 packages in 5.204s

51 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[2021-02-18 20:22:57]  INFO executing the "npm run build:cf" command...
npm WARN lifecycle The node binary used for scripts is /extbin/bin/node but npm is using /opt/nodejs/node-v10.23.1-linux-x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> fiori@0.0.1 build:cf /home/user/projects/fiori
> ui5 build preload --clean-dest --config ui5-deploy.yaml --include-task=generateManifestBundle generateCachebusterInfo

info builder:builder Building project fiori not including dependencies...
info builder:builder 🛠  (1/1) Building project fiori
.info builder:builder application fiori 🔨 (1/12) Running task escapeNonAsciiCharacters...
info builder:builder application fiori 🔨 (2/12) Running task replaceCopyright...
info builder:builder application fiori 🔨 (3/12) Running task replaceVersion...
info builder:builder application fiori 🔨 (4/12) Running task generateFlexChangesBundle...
info builder:builder application fiori 🔨 (5/12) Running task webide-extension-task-updateManifestJson...
devxUpdateManifest - datasource.uri attribute in the manifest.json file was not found or incorrect. Therefore, update this attribute to be reletive uri is irrelevant.
info builder:builder application fiori 🔨 (6/12) Running task generateManifestBundle...
info builder:builder application fiori 🔨 (7/12) Running task generateComponentPreload...
info builder:builder application fiori 🔨 (8/12) Running task createDebugFiles...
info builder:builder application fiori 🔨 (9/12) Running task uglify...
info builder:builder application fiori 🔨 (10/12) Running task generateVersionInfo...
info builder:builder application fiori 🔨 (11/12) Running task generateCachebusterInfo...
info builder:builder application fiori 🔨 (12/12) Running task ui5-task-zipper...
info builder:builder Build succeeded in 460 ms
info builder:builder Executing cleanup tasks...
[2021-02-18 20:22:58]  INFO finished building the "fiori" module
[2021-02-18 20:22:58]  INFO generating the metadata...
[2021-02-18 20:22:58]  INFO generating the "/home/user/projects/fiori/.fiori_mta_build_tmp/META-INF/mtad.yaml" file...
[2021-02-18 20:22:58]  INFO generating the MTA archive...
[2021-02-18 20:22:58]  INFO the MTA archive generated at: /home/user/projects/fiori/mta_archives/fiori_0.0.1.mtar
[2021-02-18 20:22:58]  INFO cleaning temporary files...

Terminal will be reused by tasks. 
```

**Comment by IObert** [comment]
Hi,

sorry for the late response.

The good news is that the build didn't fail, you get a success message in the end:
> [2021-02-18 20:22:58]  INFO the MTA archive generated at: /home/user/projects/fiori/mta_archives/fiori_0.0.1.mtar
> [2021-02-18 20:22:58]  INFO cleaning temporary files...

But I understand that the error messages that are related to the "pkg-config" are ugly. I believe the team fixed this problem and it doesn't happen anymore. This is also why I close the issue now, please reopen it if you see this again.
