### ISSUE TITLE
Create a Business Service with Node.js Using Visual Studio Code

### ISSUE THREAD

**Issue by amitavamitra** [SAPDocuments/Issues#214]
Sorry it does not work.  Wasted quite sometime. 

Tutorials: https://developers.sap.com/tutorials/cp-apm-nodejs-create-service.html
--------------------------
ds] - creating new project in .\my-bookshop
[cds] > adding feature 'nodejs'...
[ERROR] node C:\Program Files\nodejs\node_modules\@sap\cds-dk\bin\cds.js env json failed with code 1, internal/modules/cjs/loader.js:834
  throw err;
  ^

Error: Cannot find module 'C:\Program'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
    at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\@sap\cds-dk\lib\init\util\commandUtil.js:53:35)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

**Comment by iwonahahn** [comment]
@amitavamitra 
To which step in the tutorial you are referring? Which version of `@sap/cds-dk` are you using?
Can you please provide the output of `cds -v`?

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
