### ISSUE TITLE
Create a Basic Workflow in SAP Business Application Studio

### ISSUE THREAD

**Issue by smtpsantiago** [SAPDocuments/Issues#292]
Tutorials: https://developers.sap.com/tutorials/cp-workflow-2-create-module-cf.html
--------------------------

Hi guys, the step 3 point 3 doesn't appears that option  "about Use the down arrow to select the @workflow/workflow Module, then choose ENTER."

i try update the generator and selected to all option , the same error. 

`? 'Allo! What would you like to do? Update your generators
? Generators to update generator-basic-multitarget-application
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/generator-basic-multitarget-application - Not found
npm ERR! 404 
npm ERR! 404  'generator-basic-multitarget-application@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-04-05T07_58_57_920Z-debug.log
`

the log :

`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/opt/nodejs/node-v14.15.4-linux-x64/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   'generator-basic-multitarget-application'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose npm-session 5fb26d37a8faecf7
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/generator-basic-multitarget-application 435ms
8 http fetch GET 404 https://registry.npmjs.org/generator-basic-multitarget-application 525ms
9 silly fetchPackageMetaData error for generator-basic-multitarget-application@latest 404 Not Found - GET https://registry.npmjs.org/generator-basic-multitarget-application - Not found
10 timing stage:rollbackFailedOptional Completed in 5ms
11 timing stage:runTopLevelLifecycles Completed in 1031ms
12 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/generator-basic-multitarget-application - Not found
12 verbose stack     at /opt/nodejs/node-v14.15.4-linux-x64/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:117:15
12 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:93:5)
13 verbose statusCode 404
14 verbose pkgid generator-basic-multitarget-application@latest
15 verbose cwd /home/user/projects/onboarding
16 verbose Linux 5.4.0-5-cloud-amd64
17 verbose argv "/opt/nodejs/node-v14.15.4-linux-x64/bin/node" "/usr/local/bin/npm" "install" "--global" "generator-basic-multitarget-application"
18 verbose node v14.15.4
19 verbose npm  v6.14.10
20 error code E404
21 error 404 Not Found - GET https://registry.npmjs.org/generator-basic-multitarget-application - Not found
22 error 404
23 error 404 'generator-basic-multitarget-application@latest' is not in the npm registry.
24 error 404 You should bug the author to publish it (or use the name yourself!)
25 error 404 Note that you can also install from a
26 error 404 tarball, folder, http url, or git url.
27 verbose exit [ 1, true ]

`

**Comment by smtpsantiago** [comment]
i forgot enable workflow in space. :D
