### ISSUE TITLE
Add Automated System Tests with the SAPUI5 Test Recorder to Your CI/CD Pipeline

### ISSUE THREAD

**Issue by ncastagno-tgv** [SAPDocuments/Issues#437]
Tutorials: https://developers.sap.com/de/tutorials/cp-cicd-systemtest-recorder.html
--------------------------

I was running the tutorial step by step, and it works perfect
When I get to step 5, begins to fail the previous step with this error:

INFO: Spec started: Should navigate to the product
INFO: No elements found using by.control locator. This is what control locator last logged: Found no view with ID 'container-cart---category' and viewName '**_undefined_**' -  sap.ui.test.Opa5
No controls found so matcher pipeline processing was skipped -  sap.ui.test.pipelines.MatcherPipeline
INFO: Expectation FAILED: Failed: No element found using locator: by.control({"controlType":"sap.m.Text","viewId":"container-cart---category","properties":{"text":"Flat Watch HD32"},"interaction":{"idSuffix":"inner"}})
INFO: Spec finished: Should navigate to the product with status: FAILED

Is this "undefined" is due to a timing problem? How can it be solved?

**Comment by maximnaidenov** [comment]
Can you please check the screenshot report - what do you see at the moment of the error ?

**Comment by ncastagno-tgv** [comment]
> Can you please check the screenshot report - what do you see at the moment of the error ?

PS C:\BACKUP\cNestor\_All Techs\Mobile\GitLAB projects\UIVeri5\teched-uiveri5\uiveri5> uiveri5
INFO: @ui5/uiveri5 v1.46.3
INFO: Resolving specs
INFO: Check for latest version of: chromedriver.exe from: https://chromedriver.storage.googleapis.com/LATEST_RELEASE
INFO: Found latest version of chromedriver.exe: 91.0.4472.101
INFO: Found correct binary locally: C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\selenium\chromedriver-91.0.4472.101.exe
INFO: Executing 1 specs
[09:50:39] I/launcher - Running 1 instances of WebDriver
INFO: Opening webdriver connection with capabilities: {"browserName":"chrome","platform":"WINDOWS","chromeOptions":{"args":["--no-sandbox","--disable-dev-shm-usage","--disable-gpu","disable-infobars"]},"count":1,"loggingPrefs":{"browser":"SEVERE"}}

DevTools listening on ws://127.0.0.1:56536/devtools/browser/66101b9b-1127-49d3-a9e4-512456fd1c52
[24644:23940:0624/095044.681:ERROR:gpu_init.cc(440)] Passthrough is not supported, GL is swiftshader
[25692:29832:0624/095044.899:ERROR:device_event_log_impl.cc(214)] [09:50:44.900] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: Uno de los dispositivos conectados al sistema no funciona. (0x1F)
[25692:29832:0624/095044.901:ERROR:device_event_log_impl.cc(214)] [09:50:44.901] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: Uno de los dispositivos conectados al sistema no funciona. (0x1F)
INFO: Suite started: teched
INFO: Spec started: Should validate the home screen
INFO: Opening: https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/cart/webapp/index.html
INFO: UI5 Version: 1.90.0
INFO: UI5 Timestamp: 202105180626
INFO: Spec finished: Should validate the home screen with status: PASSED
INFO: Spec started: Should search for a product
INFO: Spec finished: Should search for a product with status: PASSED
INFO: Spec started: Should navigate to the product
INFO: No elements found using by.control locator. This is what control locator last logged: Found no view with ID 'container-cart---category' and viewName 'undefined' -  sap.ui.test.Opa5
No controls found so matcher pipeline processing was skipped -  sap.ui.test.pipelines.MatcherPipeline
INFO: Expectation FAILED: Failed: No element found using locator: by.control({"controlType":"sap.m.Text","viewId":"container-cart---category","properties":{"text":"Flat Watch HD32"},"interaction":{"idSuffix":"inner"}})
INFO: Spec finished: Should navigate to the product with status: FAILED
INFO: Spec started: should see the Home page
INFO: Spec finished: should see the Home page with status: PASSED
INFO: Spec started: should see the Product page
INFO: Spec finished: should see the Product page with status: PASSED
INFO: Suite finished: teched with status: FAILED for: 11.566s
INFO: Suite specs summary, total: 5, passed: 4, failed: 1, pending: 0, disabled: 0
INFO: Suite expectations summary, total: 3, passed: 2, failed total: 1, failed with error: 1, failed with image comparison: 0
INFO: Overall status: FAILED for: 11.589s
INFO: Overall suites summary, total: 1, passed: 0, failed: 1
INFO: Overall specs summary, total: 5, passed: 4, failed: 1, pending: 0, disabled: 0
INFO: Overall expectations summary, total: 3, passed: 2, failed total: 1, failed with error: 1, failed with image comparison: 0
[09:50:58] I/launcher - 0 instance(s) of WebDriver still running
[09:50:58] I/launcher - chrome #01 failed 1 test(s)
[09:50:58] I/launcher - overall: 1 failed spec(s)
[09:50:58] E/launcher - Process exited with error code 1
PS C:\BACKUP\cNestor\_All Techs\Mobile\GitLAB projects\UIVeri5\teched-uiveri5\uiveri5>

**Comment by maximnaidenov** [comment]
This is the log, please check the screenshot report - target\report\screenshots\report.html

**Comment by ncastagno-tgv** [comment]
> This is the log, please check the screenshot report - target\report\screenshots\report.html

![report](https://user-images.githubusercontent.com/62354561/123273531-1af22280-d4d9-11eb-823a-6b58661ca815.png)

**Comment by maximnaidenov** [comment]
Can you please copy the content of "Should navigate to the product" and also the PO methods that it uses ?

**Comment by ncastagno-tgv** [comment]
> Can you please copy the content of "Should navigate to the product" step and also the PO methods that it uses ?

    <div class="spec failed 2 hidden">
      <div class="summary">
        <div class="strong">Should navigate to the product</div>
        
        <span class="strong">Expectations</span>
        <span>Total: 1</span>
        <span>Passed: 0</span>
        <span>Failed: 1</span>
        <span>Duration: 1.3 sec</span>
        
      </div>
      
      
      <div class="step failed">
        <p class="strong">1.</p>
        <div class="content ">
          
            
            <div>Expectation FAILED: Expected &#39;&#39;  &#39;&#39;</div>
            
          
          
          
          <a href="teched-Should-navigate-to-the-product_0_fail_2021-06-24T12-50-57.png" target="_blank">
            <img data-source="teched-Should-navigate-to-the-product_0_fail_2021-06-24T12-50-57.png"/>
          </a>
          
          
          Log: <code class="log">No elements found using by.control locator. This is what control locator last logged: Found no view with ID &#39;container-cart---category&#39; and viewName &#39;undefined&#39; -  sap.ui.test.Opa5
No controls found so matcher pipeline processing was skipped -  sap.ui.test.pipelines.MatcherPipeline</code><br>
          Error stack: <code class="stack">NoSuchElementError: No element found using locator: by.control({&quot;controlType&quot;:&quot;sap.m.Text&quot;,&quot;viewId&quot;:&quot;container-cart---category&quot;,&quot;properties&quot;:{&quot;text&quot;:&quot;Flat Watch HD32&quot;},&quot;interaction&quot;:{&quot;idSuffix&quot;:&quot;inner&quot;}})
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:814:27
    at ManagedPromise.invokeCallback_ (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1376:14)
    at TaskQueue.execute_ (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3084:14)
    at TaskQueue.executeNext_ (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:3067:27)
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2927:27
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:668:7
    at processTicksAndRejections (internal/process/task_queues.js:93:5)Error
    at ElementArrayFinder.applyAction_ (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:459:27)
    at ElementArrayFinder.protractorModule.parent.exports.ElementArrayFinder.applyAction_ (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\src\reporter\actionInterceptor.js:24:25)
    at ElementArrayFinder.&lt;computed&gt; [as click] (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:91:29)
    at ElementFinder.&lt;computed&gt; [as click] (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\protractor\built\element.js:831:22)
    at Object.iSelectTheFirstProduct (C:\BACKUP\cNestor\_All Techs\Mobile\GitLAB projects\UIVeri5\teched-uiveri5\uiveri5\pages\home.js:24:11)
    at UserContext.&lt;anonymous&gt; (C:\BACKUP\cNestor\_All Techs\Mobile\GitLAB projects\UIVeri5\teched-uiveri5\uiveri5\teched.spec.js:18:24)
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:112:25
    at new ManagedPromise (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:1077:7)
    at ControlFlow.promise (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\selenium-webdriver\lib\promise.js:2505:12)
    at schedulerExecute (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:95:18)
From: Task: Run it(&quot;Should navigate to the product&quot;) in control flow
    at UserContext.&lt;anonymous&gt; (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasminewd2\index.js:94:19)
    at attempt (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4297:26)
    at QueueRunner.run (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4217:20)
    at runNext (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4257:20)
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4264:13
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4172:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
From asynchronous test: 
Error
    at Suite.&lt;anonymous&gt; (C:\BACKUP\cNestor\_All Techs\Mobile\GitLAB projects\UIVeri5\teched-uiveri5\uiveri5\teched.spec.js:17:3)
    at addSpecsToSuite (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1107:25)
    at Env.describe (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:1074:7)
    at describe (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\jasmine-core\lib\jasmine-core\jasmine.js:4399:18)
    at Object.&lt;anonymous&gt; (C:\BACKUP\cNestor\_All Techs\Mobile\GitLAB projects\UIVeri5\teched-uiveri5\uiveri5\teched.spec.js:4:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)</code>
        </div>
      </div>
      
      
    </div>

**Comment by ncastagno-tgv** [comment]
it("Should navigate to the product", function () {
    When.onTheHomePage.iSelectTheFirstProduct();
    Then.onTheProductPage.theProductTitleIsShown();
    Then.onTheProductPage.theProductCouldBeOrdered();
  });

    iSelectTheFirstProduct: function () {
      element(by.control({
          controlType: "sap.m.Text",
          viewId: "container-cart---category",
          properties: {
              text: "Flat Watch HD32"
          },
          interaction: {
              idSuffix: "inner"
          }
      })).click();
    }  

  Product: {
    actions: {
      // add action functions here
      
    },
    assertions: {
      // add assertion functions here
      theProductTitleIsShown: function () {
        var header = element(by.control({
            controlType: "sap.m.ObjectHeader",
            viewId: "container-cart---product",
            bindingPath: {
                path: "/Products('HT-6130')",
                propertyPath: "Name"
            }
        }));
        expect(header.asControl().getProperty('title')).toBe('Flat Watch HD32');
    },
    theProductCouldBeOrdered: function () {
      var button = element(by.control({
          controlType: "sap.m.Button",
          viewId: "container-cart---product",
          i18NText: {
              propertyName: "text",
              key: "addToCartShort"
          },
          interaction: {
              idSuffix: "BDI-content"
          }
      }));
      expect(button.isDisplayed()).toBeTruthy;
    }      
    }
  }

**Comment by ncastagno-tgv** [comment]
Saludos

Mgr. Néstor Castagno
I+D Manager
TGV - Excelencia en Soluciones Informáticas
• +54 11 4341-7800 (6041)
6 +54 11 3422-3487
• www.tgv.com.ar<http://www.tgv.com.ar/>



De: maximnaidenov ***@***.***>
Enviado el: jueves, 24 de junio de 2021 11:06
Para: SAPDocuments/Issues ***@***.***>
CC: Castagno, Nestor Oclides - tgv.com.ar ***@***.***>; Author ***@***.***>
Asunto: Re: [SAPDocuments/Issues] Add Automated System Tests with the SAPUI5 Test Recorder to Your CI/CD Pipeline (#437)


Can you please copy the content of "Should navigate to the product" and also the PO methods that it uses ?

**Comment by ncastagno-tgv** [comment]
I already found the problem: when doing "Press" on the text field, the Test Recorder generates "viewId: "container-cart---category"" instead of "viewName: "sap.ui.demo.cart.view.Home""
