### ISSUE TITLE
Specs not found

### ISSUE THREAD

**Issue by ncastagno-tgv** [SAPDocuments/Issues#510]
![Spec not found](https://user-images.githubusercontent.com/62354561/126792538-362cd80c-6212-468c-97b2-99aff84e7d5f.jpg)
 Stack trace:
INFO: @ui5/uiveri5 v1.46.4
INFO: Resolving specs
Error: No specs found
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\src\uiveri5.js:104:13
    at _fulfilled (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:854:54)
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:883:30
    at Promise.promise.promiseDispatch (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:816:13)       
    at C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:624:44
    at runSingle (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:137:13)
    at flush (C:\Users\ncastagno\AppData\Roaming\npm\node_modules\@ui5\uiveri5\node_modules\q\q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)

Regards, Néstor

**Comment by MichaelCzcz** [comment]
@ncastagno-tgv Hello. Can you please name the tutorial and step where you are facing this issue?

**Comment by ncastagno-tgv** [comment]
> @ncastagno-tgv Hello. Can you please name the tutorial and step where you are facing this issue?

https://developers.sap.com/de/tutorials/cp-cicd-systemtest-recorder.html
Step 3: Test the home screen

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. The issue seems to be resolved, so I am closing the issue. 

If you still have questions, feel free to reopen the issue.
