### ISSUE TITLE
Add Automated System Tests with the SAPUI5 Test Recorder to Your CI/CD Pipeline

### ISSUE THREAD

**Issue by Utkarshk7** [SAPDocuments/Issues#516]
Tutorials: https://developers.sap.com/tutorials/cp-cicd-systemtest-recorder.html
--------------------------

I am on sub step 14 of step 6 - Integrate your system tests into a CI/CD pipeline.

I have followed the steps mentioned and also replaced the GIT URL. Please help!

When I choose **Build Now**, I get below errors -

+ git checkout master
Already on 'master'
[Pipeline] libraryResource
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: **No such DSL method 'readYaml'** found among steps [archive, bat, build, catchError, checkout, deleteDir, dir, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, findBuildScans, getContext, git, input, isUnix, junit, library, libraryResource, load, lock, mail, milestone, node, parallel, powershell, properties, publishChecks, pwd, pwsh, readFile, readTrusted, resolveScm, retry, script, sh, sleep, stage, stash, step, timeout, timestamps, tm, tool, unarchive, unstable, unstash, validateDeclarativePipeline, waitUntil, warnError, withChecks, withContext, withCredentials, withEnv, withGradle, wrap, writeFile, ws] or symbols [GitUsernamePassword, all, allBranchesSame, allOf, always, ant, antFromApache, antOutcome, antTarget, any, anyOf, apiToken, architecture, archiveArtifacts, artifactManager, authorizationMatrix, batchFile, bitbucketServer, booleanParam, branch, brokenBuildSuspects, brokenTestsSuspects, buildButton, buildDiscarder, buildDiscarders, buildRetention, buildUser, buildingTag, caseInsensitive, caseSensitive, certificate, changeRequest, changelog, changeset, checkoutToSubdirectory, choice, choiceParam, cleanWs, clock, command, credentials, cron, crumb, culprits, defaultFolderConfiguration, defaultView, demand, developers, disableConcurrentBuilds, disableResume, downstream, dumb, durabilityHint, email-ext, envVars, envVarsFilter, environment, equals, expression, extendedEmailPublisher, file, fileParam, filePath, fingerprint, fingerprints, frameOptions, freeStyle, freeStyleJob, fromScm, fromSource, git, gitBranchDiscovery, gitHubBranchDiscovery, gitHubBranchHeadAuthority, gitHubExcludeArchivedRepositories, gitHubExcludeForkedRepositories, gitHubExcludePublicRepositories, gitHubForkDiscovery, gitHubIgnoreDraftPullRequestFilter, gitHubPullRequestDiscovery, gitHubSshCheckout, gitHubTagDiscovery, gitHubTopicsFilter, gitHubTrustContributors, gitHubTrustEveryone, gitHubTrustNobody, gitHubTrustPermissions, gitTagDiscovery, gitUsernamePassword, github, githubPush, gradle, headRegexFilter, headWildcardFilter, hyperlink, hyperlinkToModels, inheriting, inheritingGlobal, installSource, isRestartedRun, jdk, jdkInstaller, jgit, jgitapache, jnlp, jobBuildDiscarder, jobName, junitTestResultStorage, label, lastDuration, lastFailure, lastGrantedAuthorities, lastStable, lastSuccess, legacy, legacySCM, list, local, location, logRotator, loggedInUsersCanDoAnything, mailer, masterBuild, maven, maven3Mojos, mavenErrors, mavenGlobalConfig, mavenMojos, mavenWarnings, modernSCM, myView, namedBranchesDifferent, node, nodeProperties, nonInheriting, none, not, overrideIndexTriggers, paneStatus, parallelsAlwaysFailFast, parameters, password, pattern, permanent, pipelineTriggers, plainText, plugin, pollSCM, preserveStashes, projectNamingStrategy, proxy, pruneTags, queueItemAuthenticator, quietPeriod, rateLimit, rateLimitBuilds, recipients, requestor, resourceRoot, retainOnlyVariables, run, runParam, sSHLauncher, schedule, scmRetryCount, scriptApproval, scriptApprovalLink, search, security, shell, simpleBuildDiscarder, skipDefaultCheckout, skipStagesAfterUnstable, slave, sourceRegexFilter, sourceWildcardFilter, ssh, sshPublicKey, sshUserPrivateKey, standard, status, string, stringParam, suppressAutomaticTriggering, swapSpace, tag, teamSlugFilter, text, textParam, timestamper, timestamperConfig, timezone, tmpSpace, toolLocation, triggeredBy, unsecured, untrusted, upstream, upstreamDevelopers, userSeed, usernameColonPassword, usernamePassword, viewsTabBar, weather, withAnt, zip] or globals [abapAddonAssemblyKitCheckCVs, abapAddonAssemblyKitCheckPV, abapAddonAssemblyKitCreateTargetVector, abapAddonAssemblyKitPublishTargetVector, abapAddonAssemblyKitRegisterPackages, abapAddonAssemblyKitReleasePackages, abapAddonAssemblyKitReserveNextPackages, abapEnvironmentAssembleConfirm, abapEnvironmentAssemblePackages, abapEnvironmentCheckoutBranch, abapEnvironmentCloneGitRepo, abapEnvironmentCreateSystem, abapEnvironmentPipeline, abapEnvironmentPipelineStageATC, abapEnvironmentPipelineStageBuild, abapEnvironmentPipelineStageCloneRepositories, abapEnvironmentPipelineStageConfirm, abapEnvironmentPipelineStageInit, abapEnvironmentPipelineStageInitialChecks, abapEnvironmentPipelineStageIntegrationTests, abapEnvironmentPipelineStagePost, abapEnvironmentPipelineStagePrepareSystem, abapEnvironmentPipelineStagePublish, abapEnvironmentPullGitRepo, abapEnvironmentRunATCCheck, artifactPrepareVersion, artifactSetVersion, batsExecuteTests, buildExecute, buildSetResult, cfManifestSubstituteVariables, checkChangeInDevelopment, checkForLegacyConfiguration, checkmarxExecuteScan, checksPublishResults, cloudFoundryCreateService, cloudFoundryCreateServiceKey, cloudFoundryCreateSpace, cloudFoundryDeleteService, cloudFoundryDeleteSpace, cloudFoundryDeploy, commonPipelineEnvironment, containerExecuteStructureTests, containerPushToRegistry, containerSaveImage, currentBuild, debugReportArchive, detectExecuteScan, dockerExecute, dockerExecuteOnKubernetes, dubExecute, durationMeasure, env, fioriOnCloudPlatformPipeline, fortifyExecuteScan, gatlingExecuteTests, gaugeExecuteTests, gctsCloneRepository, gctsCreateRepository, gctsDeploy, gctsExecuteABAPUnitTests, gctsRollback, githubCheckBranchProtection, githubCommentIssue, githubCreateIssue, githubPublishRelease, githubSetCommitStatus, gitopsUpdateDeployment, hadolintExecute, handlePipelineStepErrors, healthExecuteCheck, influxWriteData, integrationArtifactDeploy, integrationArtifactDownload, integrationArtifactGetMplStatus, integrationArtifactGetServiceEndpoint, integrationArtifactTriggerIntegrationTest, integrationArtifactUpdateConfiguration, integrationArtifactUpload, jenkinsMaterializeLog, kanikoExecute, karmaExecuteTests, kubernetesDeploy, mailSendNotification, malwareExecuteScan, mavenBuild, mavenExecute, mavenExecuteIntegration, mavenExecuteStaticCodeChecks, mtaBuild, multicloudDeploy, neoDeploy, newmanExecute, nexusUpload, npmExecute, npmExecuteEndToEndTests, npmExecuteLint, npmExecuteScripts, params, pipeline, pipelineCreateScanSummary, pipelineExecute, pipelineRestartSteps, pipelineStashFiles, pipelineStashFilesAfterBuild, pipelineStashFilesBeforeBuild, piperExecuteBin, piperInitRunStageConfiguration, piperLoadGlobalExtensions, piperPipeline, piperPipelineStageAcceptance, piperPipelineStageAdditionalUnitTests, piperPipelineStageArtifactDeployment, piperPipelineStageBuild, piperPipelineStageCompliance, piperPipelineStageConfirm, piperPipelineStageInit, piperPipelineStageIntegration, piperPipelineStageMavenStaticCodeChecks, piperPipelineStagePRVoting, piperPipelineStagePerformance, piperPipelineStagePost, piperPipelineStagePromote, piperPipelineStageRelease, piperPipelineStageSecurity, piperPublishWarnings, piperStageWrapper, prepareDefaultValues, protecodeExecuteScan, readPipelineEnv, runClosures, scm, seleniumExecuteTests, setupCommonPipelineEnvironment, slackSendNotification, snykExecute, sonarExecuteScan, spinnakerTriggerPipeline, terraformExecute, testsPublishResults, tmsUpload, transportRequestCreate, transportRequestDocIDFromGit, transportRequestRelease, transportRequestReqIDFromGit, transportRequestUploadCTS, transportRequestUploadFile, transportRequestUploadRFC, transportRequestUploadSOLMAN, uiVeri5ExecuteTests, vaultRotateSecretId, whitesourceExecuteScan, writePipelineEnv, writeTemporaryCredentials, xsDeploy]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:216)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at com.sap.piper.DefaultValueCache.addDefaultsFromLibraryResources(DefaultValueCache.groovy:66)
	at com.sap.piper.DefaultValueCache.prepare(DefaultValueCache.groovy:51)
	at com.sap.piper.DefaultValueCache.prepare(DefaultValueCache.groovy)
	at com.sap.piper.ConfigurationHelper.loadStepDefaults(ConfigurationHelper.groovy:13)
	at uiVeri5ExecuteTests.call(uiVeri5ExecuteTests.groovy:27)
	at WorkflowScript.run(WorkflowScript:15)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor476.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.dispatch(CollectionLiteralBlock.java:55)
	at com.cloudbees.groovy.cps.impl.CollectionLiteralBlock$ContinuationImpl.item(CollectionLiteralBlock.java:45)
	at jdk.internal.reflect.GeneratedMethodAccessor585.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:89)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor476.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock$LocalVariable.get(LocalVariableBlock.java:39)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.LocalVariableBlock.evalLValue(LocalVariableBlock.java:28)
	at com.cloudbees.groovy.cps.LValueBlock$BlockImpl.eval(LValueBlock.java:55)
	at com.cloudbees.groovy.cps.LValueBlock.eval(LValueBlock.java:16)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Finished: FAILURE

**Comment by hmanchev** [comment]
Hi,

I don't think there is reading from yaml file in the tutorial. 

Several possible solutions can be:
1. Proper configuration of Jenkins 
2. Proper installation and configuration of SAP Project Piper

To be able to help you further, I will need ot take a look at your pipeline, so paste it here if possible.

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in the past 30 days, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
