### ISSUE TITLE
Deploy a CAP Business Application to SAP Business Technology Platform

### ISSUE THREAD

**Issue by mounikat987** [SAPDocuments/Issues#549]
Step 3: Deploy using cf push
4.Open this URL in the browser and try out the provided links, for example, .../catalog/Books

Issue:  The deployed application my-bookshop-srv is not able to load the data

**Description:** 

When we try to hit the url "https://my-bookshop-srv-shiny-capybara-qq.cfapps.us10.hana.ondemand.com/catalog/Books",
it throws  503 "service unavailable" error.

Please find logs of "my-bookshop-srv" app as below :-

 cf logs my-bookshop-srv

Retrieving logs for app my-bookshop-srv in org a175b991trial_us-5uajm35j / space dev as mounika.t@sap.com...

2021-08-11T13:44:39.97+0530 [APP/PROC/WEB/0] OUT [cds] - GET /catalog
2021-08-11T13:44:39.97+0530 [RTR/8] OUT my-bookshop-srv-shiny-capybara-qq.cfapps.us10.hana.ondemand.com - [2021-08-11T08:14:39.962202448Z] "GET /catalog HTTP/1.1" 200 0 347 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "-" "10.32.3.11:61003" x_forwarded_for:"-" x_forwarded_proto:"https" 
vcap_request_id:"240b7681-0696-4bc9-6e6c-ad4afa93f27b" response_time:0.014924 gorouter_time:0.000073 app_id:"ba89efc3-fc2f-4b66-a3ff-e1e58a077508" app_index:"0" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"bf760867-e7b5-4352-afe4-1eef7a3f13e9-611386EF-1D164C7" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" x_b3_traceid:"bfafd41135110963" x_b3_spanid:"bfafd41135110963" x_b3_parentspanid:"-" b3:"bfafd41135110963-bfafd41135110963"
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT [cds] - GET /catalog/Books
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT [hana] - effective pool configuration: {
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   min: 0,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   max: 100,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   testOnBorrow: true,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   acquireTimeoutMillis: 1000,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   softIdleTimeoutMillis: 30000,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   idleTimeoutMillis: 30000,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   evictionRunIntervalMillis: 60000,
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT   numTestsPerEvictionRun: 34
   2021-08-11T13:44:47.83+0530 [APP/PROC/WEB/0] OUT }
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR [hana] - Error: Could not establish connection for tenant "anonymous" due to error: Could not connect to any host: [ a4866278-405b-4739-b52e-2b46eefed3c9.hana.trial-us10.hanacloud.ondemand.com:443 - Client network socket disconnected before secure TLS connection was established ]
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at couldNotOpenConnectionError (/home/vcap/deps/0/node_modules/hdb/lib/protocol/ConnectionManager.js:115:13)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at tryConnect (/home/vcap/deps/0/node_modules/hdb/lib/protocol/ConnectionManager.js:35:17)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at /home/vcap/deps/0/node_modules/hdb/lib/protocol/ConnectionManager.js:42:9
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at TLSSocket.onerror (/home/vcap/deps/0/node_modules/hdb/lib/protocol/Connection.js:175:5)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at Object.onceWrapper (node:events:472:26)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at TLSSocket.emit (node:events:365:28)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at emitErrorNT (node:internal/streams/destroy:193:8)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at emitErrorCloseNT (node:internal/streams/destroy:158:3)
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR   code: 'EHDBOPENCONN'
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR }
   2021-08-11T13:44:47.84+0530 [APP/PROC/WEB/0] ERR [hana] - Could not establish connection for tenant "anonymous". Existing pool will be drained.
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR [cds] - TimeoutError: Acquiring client from pool timed out. Please review your system setup, transaction handling, and pool configuration.
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR     at ResourceRequest._fireTimeout (/home/vcap/deps/0/node_modules/@sap/cds-foss/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR     at Timeout.bound (/home/vcap/deps/0/node_modules/@sap/cds-foss/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR     at listOnTimeout (node:internal/timers:557:17)
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR     at processTimers (node:internal/timers:500:7) {
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR   statusCode: 503,
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR   id: '1056145',
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR   level: 'ERROR',
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR   timestamp: 1628669688836
   2021-08-11T13:44:48.83+0530 [APP/PROC/WEB/0] ERR }
   2021-08-11T13:44:48.83+0530 [RTR/6] OUT my-bookshop-srv-shiny-capybara-qq.cfapps.us10.hana.ondemand.com - [2021-08-11T08:14:47.822234417Z] "GET /catalog/Books HTTP/1.1" 503 0 160 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "-" "10.32.3.11:61003" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"e9b9c330-6bd9-400d-454e-28afd4b08acf" response_time:1.015246 gorouter_time:0.000058 app_id:"ba89efc3-fc2f-4b66-a3ff-e1e58a077508" app_index:"0" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"bf760867-e7b5-4352-afe4-1eef7a3f13e9-611386F7-1D16A7E" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" x_b3_traceid:"c3408cba89f20a9d" x_b3_spanid:"c3408cba89f20a9d" x_b3_parentspanid:"-" b3:"c3408cba89f20a9d-c3408cba89f20a9d"
   2021-08-11T13:44:49.20+0530 [RTR/2] OUT my-bookshop-srv-shiny-capybara-qq.cfapps.us10.hana.ondemand.com - [2021-08-11T08:14:49.188551760Z] "GET /favicon.ico HTTP/1.1" 200 0 15086 "https://my-bookshop-srv-shiny-capybara-qq.cfapps.us10.hana.ondemand.com/catalog/Books" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0" "-" "10.32.3.11:61003" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"87aeecaa-7edc-4d5c-76ed-2c4e9622b21c" response_time:0.013440 gorouter_time:0.000051 app_id:"ba89efc3-fc2f-4b66-a3ff-e1e58a077508" app_index:"0" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"bf760867-e7b5-4352-afe4-1eef7a3f13e9-611386F9-1D16B84" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" x_b3_traceid:"25b422a84f783c30" x_b3_spanid:"25b422a84f783c30" x_b3_parentspanid:"-" b3:"25b422a84f783c30-25b422a84f783c30"
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT [cds] - GET /catalog/Books
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT [hana] - effective pool configuration: {
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   min: 0,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   max: 100,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   testOnBorrow: true,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   acquireTimeoutMillis: 1000,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   softIdleTimeoutMillis: 30000,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   idleTimeoutMillis: 30000,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   evictionRunIntervalMillis: 60000,
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT   numTestsPerEvictionRun: 34
   2021-08-11T13:45:05.64+0530 [APP/PROC/WEB/0] OUT }
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR [hana] - Error: Could not establish connection for tenant "anonymous" due to error: Could not connect to any host: [ a4866278-405b-4739-b52e-2b46eefed3c9.hana.trial-us10.hanacloud.ondemand.com:443 - Client network socket disconnected before secure TLS connection was established ]
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at couldNotOpenConnectionError (/home/vcap/deps/0/node_modules/hdb/lib/protocol/ConnectionManager.js:115:13)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at tryConnect (/home/vcap/deps/0/node_modules/hdb/lib/protocol/ConnectionManager.js:35:17)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at /home/vcap/deps/0/node_modules/hdb/lib/protocol/ConnectionManager.js:42:9
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at TLSSocket.onerror (/home/vcap/deps/0/node_modules/hdb/lib/protocol/Connection.js:175:5)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at Object.onceWrapper (node:events:472:26)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at TLSSocket.emit (node:events:365:28)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at emitErrorNT (node:internal/streams/destroy:193:8)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at emitErrorCloseNT (node:internal/streams/destroy:158:3)
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR   code: 'EHDBOPENCONN'
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR }
   2021-08-11T13:45:05.65+0530 [APP/PROC/WEB/0] ERR [hana] - Could not establish connection for tenant "anonymous". Existing pool will be drained.
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR [cds] - TimeoutError: Acquiring client from pool timed out. Please review your system setup, transaction handling, and pool configuration.
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR     at ResourceRequest._fireTimeout (/home/vcap/deps/0/node_modules/@sap/cds-foss/node_modules/generic-pool/lib/ResourceRequest.js:62:17)
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR     at Timeout.bound (/home/vcap/deps/0/node_modules/@sap/cds-foss/node_modules/generic-pool/lib/ResourceRequest.js:8:15)
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR     at listOnTimeout (node:internal/timers:557:17)
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR     at processTimers (node:internal/timers:500:7) {
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR   statusCode: 503,
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR   id: '1056145',
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR   level: 'ERROR',
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR   timestamp: 1628669706643
   2021-08-11T13:45:06.64+0530 [APP/PROC/WEB/0] ERR }
   2021-08-11T13:45:06.64+0530 [RTR/4] OUT my-bookshop-srv-shiny-capybara-qq.cfapps.us10.hana.ondemand.com - [2021-08-11T08:15:05.630473785Z] "GET /catalog/Books HTTP/1.1" 503 0 160 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36" "-" "10.32.3.11:61003" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"48da815a-e56f-4143-77da-768a893359d1" response_time:1.013963 gorouter_time:0.000098 app_id:"ba89efc3-fc2f-4b66-a3ff-e1e58a077508" app_index:"0" x_cf_routererror:"-" x_correlationid:"-" tenantid:"-" sap_passport:"-" x_scp_request_id:"5a599ba2-129f-477a-8154-d6984559f455-61138708-195185E" x_cf_app_instance:"-" x_forwarded_host:"-" x_custom_host:"-" x_ssl_client:"-" x_ssl_client_session_id:"-" x_ssl_client_verify:"-" x_ssl_client_subject_dn:"-" x_ssl_client_subject_cn:"-" x_ssl_client_issuer_dn:"-" x_ssl_client_notbefore:"-" x_ssl_client_notafter:"-" x_b3_traceid:"bcdd51489eaeb64b" x_b3_spanid:"bcdd51489eaeb64b" x_b3_parentspanid:"-" b3:"bcdd51489eaeb64b-bcdd51489eaeb64b"

![image](https://user-images.githubusercontent.com/33411431/128994632-4b2a0aad-0574-40c5-815a-7b73c8c7a3eb.png)

Note ** :** my hana instance is up & running. I checked multiple times.

![image](https://user-images.githubusercontent.com/33411431/128995694-4ad2b924-6812-4129-ab06-f0be76158c49.png)

**Comment by iwonahahn** [comment]
Hi @mounikat987,

Sorry for the late reply, I was on vacation. I have to test the tutorial with the latest CAP release to reproduce your issue and will get back to you asap.

Best regards,
Iwona

**Comment by iwonahahn** [comment]
Hi @mounikat987,

Using the latest version of CAP 
![2021-09-06_13-49-27](https://user-images.githubusercontent.com/22098308/132213105-0ae516a4-8934-4ba6-b98f-ab1ae74a5b0d.png)
it works and I can access the data from `...catalogs/Books`.
![2021-09-06_13-47-26](https://user-images.githubusercontent.com/22098308/132213148-72ed046e-ffc7-4b9d-a022-f2fe3705d517.png)

Therefore I will close this issue cause the new testing cycle will start soon.

Best regards,
Iwona
