### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by mfadili** [SAPDocuments/Issues#551]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------

At STEP 10, the following command fails:
> fiori add deploy-config cf

info Add:Deploy-config Using: @sap/fiori:deploy-config
info Add:Flp-config Using: @sap/fiori:flp-config
Fiori tools CLI.
Adding deploy-config to the project.
? Destination name cpapp-app-srv
node:events:371
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'addRoutingModules' of undefined
    at e.exports._updateMtaConfig (/usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/cf/index.js:1:35532)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async e.exports._writeDeploymentConfigChanges (/usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/cf/index.js:1:32089)
    at async e.exports.writing (/usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/cf/index.js:1:31846)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/usr/local/lib/node_modules/@sap/generator-fiori/node_modules/yeoman-generator/lib/index.js:791:20)

**Comment by matheusbrasil** [comment]
Hey @mfadili, please check the mta.yaml indentation. I believe that when you've done step 7, you may have broken the indentation.

**Comment by iwonahahn** [comment]
Hi @mfadili,

We haven't heard from you in a while, so we are closing the issue.

Best regards,
Iwona
