### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by zeitiger** [SAPDocuments/Issues#661]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------
Step 10 and 12 failed with following output. Problem is independent of Node14 or Node16.
```
fiori add deploy-config cf         
Debugger attached.
Adding deploy-config to the project.
info Add:Deploy-config Using: @sap/fiori:deploy-config
Debugger attached.
? Destination name cpapp-app-srv
Waiting for the debugger to disconnect...
node:events:368
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read properties of undefined (reading 'addRoutingModules')
    at e.exports._updateMtaConfig (/usr/local/Cellar/node/16.11.1/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/cf/index.js:1:11959)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async e.exports._writeDeploymentConfigChanges (/usr/local/Cellar/node/16.11.1/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/cf/index.js:1:8525)
    at async e.exports.writing (/usr/local/Cellar/node/16.11.1/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/cf/index.js:1:8282)
Emitted 'error' event on  instance at:
    at Immediate.<anonymous> (/usr/local/Cellar/node/16.11.1/lib/node_modules/@sap/generator-fiori/node_modules/yeoman-generator/lib/index.js:791:20)
    at processImmediate (node:internal/timers:464:21)
Do you need to install @sap/generator-fiori globally?
npm install -g @sap/generator-fiori
OR
yarn global add @sap/generator-fiori

Waiting for the debugger to disconnect...
```

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
