### ISSUE TITLE
Add the SAP Launchpad Service

### ISSUE THREAD

**Issue by vvnsmc** [SAPDocuments/Issues#680]
Tutorials: https://developers.sap.com/tutorials/btp-app-launchpad-service.html
--------------------------
Error in executing step Step 12: Add SAPUI5 freestyle Mitigations application

cmd: fiori add deploy-config cf
destination name:: cpapp-app-srv

error:
`PS C:\Users\lenovo\cpapp\app\mitigations> fiori add deploy-config cf
Adding deploy-config to the project.
info Add:Deploy-config Using: @sap/fiori:deploy-config
? Destination name cpapp-app-srv
events.js:377
throw er; // Unhandled 'error' event
^

TypeError: Cannot read property 'addRoutingModules' of undefined
at e.exports._updateMtaConfig (C:\Users\lenovo\AppData\Roaming\npm\node_modules@sap\generator-fiori\generators\deployment-generator\cf\index.js:1:11959)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async e.exports._writeDeploymentConfigChanges (C:\Users\lenovo\AppData\Roaming\npm\node_modules@sap\generator-fiori\generators\deployment-generator\cf\index.js:1:8525)
at async e.exports.writing (C:\Users\lenovo\AppData\Roaming\npm\node_modules@sap\generator-fiori\generators\deployment-generator\cf\index.js:1:8282)
Emitted 'error' event on Generator instance at:
at Immediate. (C:\Users\lenovo\AppData\Roaming\npm\node_modules@sap\generator-fiori\node_modules\yeoman-generator\lib\index.js:791:20)
at processImmediate (internal/timers.js:464:21)
Do you need to install @sap/generator-fiori globally?
npm install -g @sap/generator-fiori
OR
yarn global add @sap/generator-fiori`

**Comment by MichaelCzcz** [comment]
Thank you for your feedback. We haven't heard from you in a while, so we are closing the issue. 

If you still have questions, feel free to reopen the issue.
