### ISSUE TITLE
Issue with SQLite

### ISSUE THREAD

**Issue by JohannesLust** [SAPDocuments/Issues#9]
Tutorial: https://developers.sap.com/tutorials/cp-cap-java-reusable-service.html
--------------------------

After running 
_npm install --save-dev sqlite3_ 
as explained in step 5 of above tutorial, I try to run 
_cds deploy --to sqlite_

The latter command can't be executed successfully. Instead, following error message is displayed:
_[ERROR] Cannot find module 'sqlite3'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Promise (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:21:17)
    at new Promise (<anonymous>)
    at _new (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:19:10)
    at SQLiteDatabase.acquire (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/sqlite/Service.js:130:19)
    at SQLiteDatabase.begin (/extbin/npm/globals/lib/node_modules/@sap/cds-runtime/lib/db/Service.js:48:23)
    at Function.for (/extbin/npm/globals/lib/node_modules/@sap/cds/lib/srv/Transaction.js:47:26)_

**Comment by iwonahahn** [comment]
Hi Johannes,

Please see the comment in this [issue](https://github.com/SAPDocuments/Tutorials/issues/6240#issuecomment-734740827). Maybe this solves your problem and you can continue. Otherwise please get back here.

Best regards,
Iwona

**Comment by JohannesLust** [comment]
Hi Iwona,

many thanks for your support. It works when trying to run the following command as explained in the other issue:
unset NODE_PATH

Thanks and Regards,
Johannes
